name: Local Config
version: 1.0.0
schema: v1
models:
  - name: Gemini 3.1 Flash Lite
    provider: gemini
    model: gemini-3.1-flash-lite-preview
    apiKey: AQ.Ab8RN6IhhK7p-447g1ysiBblVDRAUZ3MDx_iBruPEGZnWz_KMw
  - name: Gemini 3.1 Pro
    provider: gemini
    model: gemini-3.1-pro-preview
    apiKey: AQ.Ab8RN6IhhK7p-447g1ysiBblVDRAUZ3MDx_iBruPEGZnWz_KMw
  - name: Gemini 3 Flash
    provider: gemini
    model: gemini-3-flash-preview
    apiKey: AQ.Ab8RN6IhhK7p-447g1ysiBblVDRAUZ3MDx_iBruPEGZnWz_KMw
  - name: Gemini 2.5 Flash Lite
    provider: gemini
    model: gemini-2.5-flash-lite
    apiKey: AQ.Ab8RN6IhhK7p-447g1ysiBblVDRAUZ3MDx_iBruPEGZnWz_KMw
